ancho = int(input("Introduce el ancho: "))
alto = float(input("Introduce el alto: "))
print(ancho / alto, type(ancho / alto))
print(ancho // 2, type(ancho // 2))
print(ancho / 2, type(ancho / 2))
print(ancho * 2, type(ancho * 2))
print(ancho * alto, type(ancho * alto))
print((5 + 1) * 3, type((5 + 1) * 3))
print((5 + 1) / 3, type((5 + 1) / 3))
